# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\pylearn\Demo\MainDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainDemo(object):
    def setupUi(self, MainDemo):
        MainDemo.setObjectName("MainDemo")
        MainDemo.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.pbClose = QtWidgets.QPushButton(self.centralwidget)
        self.pbClose.setGeometry(QtCore.QRect(120, 110, 271, 91))
        self.pbClose.setObjectName("pbClose")
        MainDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainDemo)
        self.statusbar.setObjectName("statusbar")
        MainDemo.setStatusBar(self.statusbar)

        self.retranslateUi(MainDemo)
        QtCore.QMetaObject.connectSlotsByName(MainDemo)

    def retranslateUi(self, MainDemo):
        _translate = QtCore.QCoreApplication.translate
        MainDemo.setWindowTitle(_translate("MainDemo", "MainWindow"))
        self.pbClose.setText(_translate("MainDemo", "Close"))
